#!/bin/sh
# new build script
# clean old build remains
cd ~/jfx_build/build_dir/jar
rm *.jar
cd ~/jfx_build
rm -r -f output
cd ~/jfx_build/build_dir/javafx-mods
rm *.jar
# build both jar w/o deps (to collect and copy platform dependent jfx modules)
# and then build fat jar
cd ~/code/jfxchess
mvn clean package
# copy fat jar and platform dependent jfx modules to build dir
cp target/jfxchess-4.5-jar-with-dependencies.jar ~/jfx_build/build_dir/jar
cp target/javafx-mods/*.* ~/jfx_build/build_dir/javafx-mods
# copy app icon
cp ~/code/jfxchess/src/main/resources/icons/app_icon@3x.png ~/jfx_build/build_dir/linux/app_icon.png
# copy desktop entry
cp ~/code/jfxchess/linux_desktop_entry/jfxchess.desktop ~/jfx_build/build_dir/linux/
# copy splash image
cp ~/code/jfxchess/splash.png ~/jfx_build/build_dir/jar/
# assemble with jpackage
cd ~/jfx_build
jpackage --module-path build_dir/javafx-mods  --add-modules javafx.controls,javafx.swing --java-options '-splash:$APPDIR/splash.png' --type deb -n jfxchess -i build_dir/jar --main-jar jfxchess-4.5-jar-with-dependencies.jar -d output --icon build_dir/linux/app_icon.png --resource-dir build_dir/linux --linux-menu-group games --linux-shortcut --license-file build_dir/LICENSE.TXT --about-url https://github.com/asdfjkl/jfxchess --linux-app-release 4.5 --main-class org.asdfjkl.jfxchess.gui.Main
