"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['jerry.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': False, 'iconfile': 'MyIcon.icns'}

setup(
    app=APP,
    name='Jerry',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
