from PyQt4.QtGui import *
from PyQt4.QtCore import *

class DialogNewGame(QDialog):

    def __init__(self, parent=None):
        super(DialogNewGame,self).__init__(parent)
        self.setWindowTitle("New Game")

        self.rb_plays_white = QRadioButton("White")
        self.rb_plays_black = QRadioButton("Black")
        self.rb_plays_white.setChecked(True)

        lbl_choose_side = QLabel("Choose your side:")
        btnGroupSide = QButtonGroup(self)
        btnGroupSide.addButton(self.rb_plays_white)
        btnGroupSide.addButton(self.rb_plays_black)
        lbl_choose_side.setAlignment(Qt.AlignBottom)
        hboxSide = QHBoxLayout()
        hboxSide.addWidget(self.rb_plays_white)
        hboxSide.addWidget(self.rb_plays_black)
        hboxSide.setAlignment(Qt.AlignLeft)

        lbl_elo = QLabel("Computer Strength")
        lbl_elo.setAlignment(Qt.AlignBottom)
        self.lbl_slider_value = QLabel("1500")
        hboxSlider = QHBoxLayout()
        self.slider = QSlider(Qt.Horizontal, self)
        self.slider.setRange(0,19)
        self.slider.setTickInterval(1)
        self.slider.setTickPosition(2)
        self.slider.setValue(3)
        hboxSlider.addWidget(self.slider)
        hboxSlider.addWidget(self.lbl_slider_value)

        btnGroupTime = QButtonGroup(self)
        hboxFixedTime = QHBoxLayout()
        lbl_fixed = QLabel("Untimed Game")
        lbl_fixed.setAlignment(Qt.AlignBottom)
        self.rb_untimed = QRadioButton("Computer thinks for")
        self.rb_untimed.setChecked(True)
        btnGroupTime.addButton(self.rb_untimed)
        self.think_secs = QSpinBox()
        self.think_secs.setSuffix("sec(s)")
        self.think_secs.setMaximum(99)
        self.think_secs.setValue(1)
        hboxFixedTime.addWidget(self.rb_untimed)
        hboxFixedTime.addWidget(self.think_secs)
        hboxFixedTime.addStretch(1)

        lbl_blitz = QLabel("Timed Game")
        lbl_blitz.setAlignment(Qt.AlignBottom)
        blitzGrid = QGridLayout()
        self.rb_blitz1 = QRadioButton("1 min")
        self.rb_blitz2_12 = QRadioButton("2 min + 12s inc")
        self.rb_blitz3_5 = QRadioButton("3 min + 5s inc")
        self.rb_blitz5 = QRadioButton("5 min")
        self.rb_blitz15 = QRadioButton("15 min")
        self.rb_blitz30 = QRadioButton("30 min")
        blitzGrid.addWidget(self.rb_blitz1,1,1)
        blitzGrid.addWidget(self.rb_blitz2_12,2,1)
        blitzGrid.addWidget(self.rb_blitz3_5,3,1)
        blitzGrid.addWidget(self.rb_blitz5,1,2)
        blitzGrid.addWidget(self.rb_blitz15,2,2)
        blitzGrid.addWidget(self.rb_blitz30,3,2)

        btnGroupTime.addButton(self.rb_blitz1)
        btnGroupTime.addButton(self.rb_blitz2_12)
        btnGroupTime.addButton(self.rb_blitz3_5)
        btnGroupTime.addButton(self.rb_blitz5)
        btnGroupTime.addButton(self.rb_blitz15)
        btnGroupTime.addButton(self.rb_blitz30)

        buttonBox = QDialogButtonBox(QDialogButtonBox.Ok| QDialogButtonBox.Cancel)

        layout = QVBoxLayout()
        layout.addWidget(lbl_choose_side)
        layout.addLayout(hboxSide)
        layout.addSpacing(20)
        layout.addWidget(lbl_elo)
        layout.addLayout(hboxSlider)
        layout.addSpacing(20)
        layout.addWidget(lbl_fixed)
        layout.addLayout(hboxFixedTime)
        layout.addSpacing(20)
        layout.addWidget(lbl_blitz)
        layout.addLayout(blitzGrid)

        layout.addWidget(buttonBox)
        self.setLayout(layout)

        self.slider.valueChanged.connect(self.set_lbl_value)
        self.connect(buttonBox, SIGNAL("accepted()"),self, SLOT("accept()"))
        self.connect(buttonBox, SIGNAL("rejected()"),self, SLOT("reject()"))
        self.resize(370, 150)

    def set_lbl_value(self,val):
        self.lbl_slider_value.setNum(1200+(val*100))